[project]
name = "advent-of-code-25"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "pytest>=9.0.2",
]

[pytest]
addopts = ["--doctest-modules"]
doctest_optionflags = ["NORMALIZE_WHITESPACE", "IGNORE_EXCEPTION_DETAIL"]
